# Generated by Django 5.0.4 on 2026-04-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('resume', models.CharField(max_length=255)),
                ('contenu', models.TextField()),
                ('image', models.ImageField(upload_to='articles/')),
                ('categorie', models.CharField(choices=[('equipements', 'Équipements industriels'), ('materiaux', 'Matériaux'), ('pieces', 'Pièces de rechange')], max_length=32)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('publie', models.BooleanField(default=False)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['-date_publication'],
            },
        ),
    ]
