# Generated by Django 5.0.4 on 2026-04-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categorie',
            field=models.CharField(choices=[('informatique', 'Informatique'), ('electronique', 'Électronique'), ('electromenager', 'Électroménager'), ('produits_chimiques', 'Produits chimiques'), ('autres', 'Autres')], max_length=32),
        ),
    ]
