# Generated by Django 5.0.4 on 2026-05-06 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('contenu', models.TextField()),
                ('image', models.ImageField(upload_to='articles/')),
                ('categorie', models.CharField(choices=[('informatique', 'Informatique'), ('electronique', 'Électronique'), ('electromenager', 'Électroménager'), ('produits_chimiques', 'Produits chimiques'), ('autres', 'Autres')], max_length=32)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('publie', models.BooleanField(default=False)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['-date_publication'],
            },
        ),
    ]
