# Generated by Django 5.0.4 on 2026-05-06 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0002_alter_article_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='resume',
        ),
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
